### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by reinstall890** [vaaski/telegram-ytdl#108]
Command failed with exit code 1: yt-dlp -J -f b --no-playlist https://youtu.be/e50XCpjSVgU?si=2FuxQWOmhQfGXeth
ERROR: [youtube] e50XCpjSVgU: Sign in to confirm you’re not a bot. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
null

**Comment by vaaski** [comment]
This is an upstream issue, refer to https://github.com/yt-dlp/yt-dlp/issues/10128 and https://github.com/yt-dlp/yt-dlp/issues/3766
