### ISSUE TITLE
HttpError: Network request for 'setWebhook' failed!

### ISSUE THREAD

**Issue by Ppang0405** [vaaski/telegram-ytdl#110]
Step to reproduce

1. clone the project, 
2. run npm install
3. create .env and fill values
4. npm run dev

Error throw from node_modules/grammy/out/core/error.js:85
Idk what happens here. Do anyone get this issue and how can I resolve this?

**Comment by vaaski** [comment]
This is meant to be run inside docker and I am not planning to make it work outside of that environment. Refer to [the instructions in the readme](https://github.com/vaaski/telegram-ytdl#hosting).

I suspect you've misconfigured the WEBHOOK_URL or don't have a telegram API server running.
