### ISSUE TITLE
Soundcloud long music timeout

### ISSUE THREAD

**Issue by Vozf** [vaaski/telegram-ytdl#93]
when I try to dl longer music for example this one

https://soundcloud.com/acris-official-music/ascension-midnight-tape-ep-3-drum-bass-mix
I get a timeout after 500 sec and an error. While it works fine with normal 3min tracks

**Comment by vaaski** [comment]
Hey, thanks for checking out my project!

This is indeed an interesting issue that I was able to reproduce. I've tested the download flow outside of the bot environment of the bot and it seems to work fine, although pretty slow. Soundcloud seems to limit the download speed to around 200 KiB/s.

I will try to investigate this issue this week, and until then I can firmly recommend [cobalt.tools](https://cobalt.tools/) as a solid web-based fallback, even seems to get slightly faster download speeds.

**Comment by vaaski** [comment]
Sorry, but I don't have the spare time available at the moment to look too deeply into this. I'm just going to blame SoundCloud's throttling.
