### ISSUE TITLE
Requested format is not available

### ISSUE THREAD

**Issue by Saleh-Mumtaz** [vaaski/telegram-ytdl#94]
Hi, thank you for your great project. I run into this error each time I send any link.

![image](https://github.com/user-attachments/assets/88964ccf-31fa-4031-8ce3-ea12e76c350e)
Containers are running. ufw rules allowed 8081 and 8082 ports. (I changed 8443 to 8082, I am using that for another service.)

But it works perfectly with tiktok.

![image](https://github.com/user-attachments/assets/60dc68d9-a160-4c54-b7ee-801423578300)

And youtube music

![image](https://github.com/user-attachments/assets/f289a905-cb93-42a7-8c0d-69cf2afc27ba)

Also I want to know if it is possible to have a youtube video as mp3, and if yes how can I do that.

Thanks

**Comment by salehMomtaz** [comment]
Nice invalid request handling 😁

![image](https://github.com/user-attachments/assets/c788bf20-a555-429d-b9fa-9bf17bd27d36)

**Comment by vaaski** [comment]
Hey, I tried to URL from your screenshot (`https://youtu.be/cuN82OBSD9s`) and couldn't replicate the issue. YouTube changes things around all the time and the folks at [yt-dlp](https://github.com/yt-dlp/yt-dlp) try their best to keep up. I've included an auto-updater that runs daily to get the most recent nightly build, so things might stop and start working again on their own at any time.

As for downloading as MP3, the way I designed the bot unfortunately doesn't allow per-download format selection and would require a lot of changes to do so. For YouTube specifically though, you should be able to just replace `www.` with `music.` as I've specifically created a check for YouTube music URLs.

So if you change `https://www.youtube.com/watch?v=cuN82OBSD9s` to `https://music.youtube.com/watch?v=cuN82OBSD9s` it downloads as a MP3.

**Comment by salehMomtaz** [comment]
Yes, this doesn't happen now. Nightly build must have fixed it.
