### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Abolfazl123** [vaaski/telegram-ytdl#95]
Hi, I have a question. How can I remove the restriction for general users to use the bot? I'm referring to the `ADMIN_ID` code.

**Comment by vaaski** [comment]
I am pretty sure that the actual value you're looking for is `WHITELISTED_IDS`. Those are the Telegram user IDs of users allowed to download stuff with the bot. I've just pushed an update (ba2ad2de4571ec28a4fe8ff3ae93618ec31752ac) which enables you to leave the value blank to allow all users.

**Comment by Abolfazl123** [comment]
Hello, thank you! If possible, please create a complete tutorial for setting up a Telegram bot from scratch, either as a video or text. That would be great! Setting it up is quite difficult for me, from installing Docker to obtaining the API from Telegram. I’d really appreciate your help. Thank you!

**Comment by vaaski** [comment]
Sorry for getting back so late, but I've had a [basic tutorial for setting up the bot in the readme](https://github.com/vaaski/telegram-ytdl#installation) for a while. I'm sure you can find more in-depth instructions for each step online. Googling stuff is a big part of being a developer, I'm sure you can figure it out and learn more compared to if I provide detailed steps ;)
